server:
  shutdown: graceful

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: good_change
  datasource:
    url: jdbc:mysql://localhost:3306/good_change?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: goodchange
    password: Gx9#mK2$vL8@nQ4!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10      # 최대 커넥션 수
      minimum-idle: 10            # 최소 유지 커넥션 수
      connection-timeout: 10000  # 커넥션 대기 시간 (30초)
      idle-timeout: 600000       # 유휴 커넥션 유지 시간 (10분)
      max-lifetime: 1800000      # 커넥션 최대 유지 시간 (30분)
      pool-name: HikariPool-GoodChange
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    export:
      prometheus:
        metrics:
          export:
            enabled: true
    enable:
      hikaricp: true    # ✅ 추가
      jvm: true        # ✅ 추가
      process: true    # ✅ 추가
      system: true     # ✅ 추가


cors:
  allowed-origins: http://localhost:8000

logging:
  level:
    org.best: INFO