spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: bizline11        # @naver.com 빼고 아이디만
    password: 0816line114
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
    default-encoding: UTF-8
  profiles:
    active: local  # 기본값 로컬

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.best.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: good-change-secret-key-must-be-at-least-256-bits-long-for-security
  expiration: 14400000